---
#apache server with define extra variables in the ansible roles
- name: install Apache and upload my Web page
  hosts: "{{ HOSTS }}"
  become: yes

  roles:
    - { role: deploy_apache_webserver, when: ansible_system == 'Linux' }
